@startuml

'--------------'
'Hidden members'
'--------------'
hide empty members

'----'
'Move'
'----'
abstract class PieceType {
    - color
    - hasBeenKickedOffTheBoard
    - isBeingPromoted
    + getName()
    + getNextPawnPromotion()
    + getValue()
    + isValidMove()
    + setPieceTypeSpecificAttributes()
}

class Bishop {
    - {static} bishopIsValidMoveRulesEngine
}

class IsValidMoveParameter {
    - chessboard
    - from
    - to
    - isOpponent
}

interface RulesEngine {
    - rules
    + addRule()
    + process()
}

interface Rule {
    + isApplicable()
    + getResult()
}

'---------'
'Relations'
'---------'
PieceType <|-down- Bishop
Bishop *-- BishopIsValidMoveRulesEngine
BishopIsValidMoveRulesEngine -up-|> RulesEngine
BishopIsValidMoveRulesEngine -up-|> PieceTypeSharedRules
BishopIsValidMoveRulesEngine .down[#blue].> IsValidMoveParameter
HasEmptyParametersRule -up-* BishopIsValidMoveRulesEngine
IsFriendlyFireRule -up-* BishopIsValidMoveRulesEngine
IsJumpingRule -up-* BishopIsValidMoveRulesEngine
IsMovingIntoCheckRule -up-* BishopIsValidMoveRulesEngine
BishopIsValidBasicMoveRule -up-* BishopIsValidMoveRulesEngine
IsNotValidRule -up-* BishopIsValidMoveRulesEngine
HasEmptyParametersRule --|> Rule
IsFriendlyFireRule --|> Rule
IsJumpingRule --|> Rule
IsMovingIntoCheckRule --|> Rule
BishopIsValidBasicMoveRule --|> Rule
IsNotValidRule --|> Rule

@enduml
