@startuml

'--------------'
'Hidden members'
'--------------'
hide empty members

'----------'
'Chessboard'
'----------'
class Chessboard {
    - BackgroundColorRulesEngine
    - ChessboardValueRulesEngine
    - fields
    - kingField
    - opponentKingField
    - level
    - fromParentToChildMove
    - children
    + create()
    + createEmpty()
    + createOneStepBeyond()
    + enableValidMoves()
    + getField()
    + resetValidMoves()
    + setKingFieldColors()
}

class BackgroundColorRulesEngine {

}

class Field {
    - BackgroundColorRulesEngine
    - id
    - code
    - coordinates
    - pieceType
    - backgroundColor
    - value
    - relativeValue
    - isValidFrom
    - hasValidTo
    - isAttacking
    - isUnderAttack
    - isCheckMate
    - isStaleMate
    + isActivePlayerField()
    + isInCheckNow()
    + isMovingIntoCheck()
    + isNotAbleToMove()
    + isValid()
    + setAttackingColors()
}

class Move {
    - from
    - to
    + isDuringAMove()
    + isFrom()
    + isValid()
    + setFrom()
    + setTo()
}

class Coordinates {
    - x
    - y
    + create()
    + createCode()
    + createId()
}

class PieceType {
    - color
    - hasBeenKickedOffTheBoard
    - isPawnBeingPromoted
    + getName()
    + getNextPawnPromotion()
    + getValue()
    + isValidMove()
    + setPieceTypeSpecificAttributes()
}

interface RulesEngine {
    - rules
    + addRule()
    + process()
}

interface Rule {
    + hasResult()
    + createResult()
}

enum BackgroundColor {
    + LIGHT
    + DARK
    + ATTACKING
    + CHECKMATE
    + STALEMATE
    - awtColor

}

'---------'
'Relations'
'---------'
Chessboard *-up- BackgroundColorRulesEngine
Chessboard *-right- ChessboardValueRulesEngine
Chessboard *-left- Field
Chessboard *-right- Move
Chessboard "0..*"--o Chessboard
Field *-up- BackgroundColorRulesEngine
Field *-left- Coordinates
Field *-- PieceType
Field --* Move
BackgroundColorRulesEngine *-up- HardwoodRule
BackgroundColorRulesEngine *-up- FieldValueRule
BackgroundColorRulesEngine *-up- AttackingRule
BackgroundColorRulesEngine *-up- StalemateRule
BackgroundColorRulesEngine *-up- CheckmateRule
BackgroundColorRulesEngine -left-|> RulesEngine
HardwoodRule -up-|> Rule
FieldValueRule -up-|> Rule
AttackingRule -up-|> Rule
StalemateRule -up-|> Rule
CheckmateRule -up-|> Rule
HardwoodRule .down[#blue].> BackgroundColor
AttackingRule .down[#blue].> BackgroundColor
StalemateRule .down[#blue].> BackgroundColor
CheckmateRule .down[#blue].> BackgroundColor

@enduml
