@startuml

'--------------'
'Hidden members'
'--------------'
hide empty members

'-----------'
'Annotations'
'-----------'
annotation SpringBootApplication

'-----------'
'Application'
'-----------'
class Application {
    - {static} frontendChessboardBuilder
    + {static} main()
}

'-----'
'Swing'
'-----'
interface ActionListener{
}

interface MouseListener{
}

class FrontendChessboard{
    - game
    - gameService
    - frontendFields
    + createGrid()
    + mousePressed()
}

class FrontendChessboardBuilder {
    - frontendChessboard
    + initialize()
    + createFields()
    + updateFields()
    + build()
}

class FrontendField {
    + updateGraphics()
    + createButtonId()
    + reset()
}

class GameService {
    + createGame()
    + handleButtonClick()
    + resetValidMoves()
}

'---------'
'Relations'
'---------'
JFrame <|-- FrontendChessboard
JButton <|-- FrontendField
ActionListener <|-- FrontendChessboard
MouseListener <|-- FrontendChessboard
FrontendChessboard *-- FrontendChessboardBuilder : < updates board
FrontendChessboard -left-* FrontendField : consists of >
FrontendChessboard -right-o GameService : < updates game
FrontendChessboardBuilder *-- Application : < creates a board
Application ..> SpringBootApplication
Application ..> SpringApplicationBuilder : < builds Spring Application instance

@enduml
