@startuml

'--------------'
'Hidden members'
'--------------'
hide empty members

'----'
'Game'
'----'
class GameService {
    + createGame()
    + handleButtonClick()
    + resetValidMoves()
}

class Game {
    - {static} moveBuilder
    - chessboard
    - players
    - move
    + {static} create()
    + {static} restart()
    + changeTurn()
    + handleButtonClick()
}

class Chessboard {
    + create()
    + createEmpty()
    + createOneStepBeyond()
    + getField()
    + getKingField()
    + setKingFieldColors()
    + setValidMoveColors()
    + enableValidMoves()
    + resetValidMoves()
}

class Move {
    - pieceType
    - from
    - to
    + isDuringAMove()
    + isFrom()
    + isValid()
    + setFrom()
    + setTo()
}

class MoveBuilder {
    + performFromMove()
    + performToMove()
    + performResetMove()
}

class Player {
    - playerColor
    - playerType
}

'---------'
'Relations'
'---------'
GameService ..> Game
GameService ..> Chessboard
Game -left-* Chessboard
Game -down-* MoveBuilder
MoveBuilder .up.> Move
Game -right-* Move
Game -up-* Player

@enduml
