@startuml

'--------------'
'Hidden members'
'--------------'
hide empty members

'----'
'Move'
'----'
abstract class PieceType {
    - color
    - hasBeenKickedOffTheBoard
    - isBeingPromoted
    + getName()
    + getNextPawnPromotion()
    + getValue()
    + isValidMove()
    + setPieceTypeSpecificAttributes()
}

class King {
    - {static} kingIsValidMoveRulesEngine
}

class IsValidMoveParameter {
    - chessboard
    - from
    - to
    - isOpponent
}

interface RulesEngine {
    - rules
    + addRule()
    + process()
}

interface Rule {
    + isApplicable()
    + getResult()
}

'---------'
'Relations'
'---------'
PieceType <|-down- King
King *-- KingIsValidMoveRulesEngine

KingIsValidMoveRulesEngine -up-|> RulesEngine
KingIsValidMoveRulesEngine .left[#blue].> IsValidMoveParameter

HasEmptyParametersRule -up-* KingIsValidMoveRulesEngine
IsFriendlyFireRule -up-* KingIsValidMoveRulesEngine
IsJumpingRule -up-* KingIsValidMoveRulesEngine
IsMovingIntoCheckRule -up-* KingIsValidMoveRulesEngine
KingIsValidBasicMoveRule -up-* KingIsValidMoveRulesEngine
KingIsValidCastlingRule -up-* KingIsValidMoveRulesEngine
IsNotAValidMoveRule -up-* KingIsValidMoveRulesEngine

HasEmptyParametersRule --|> Rule
IsFriendlyFireRule --|> Rule
IsJumpingRule --|> Rule
IsMovingIntoCheckRule --|> Rule
KingIsValidBasicMoveRule --|> Rule
KingIsValidCastlingRule --|> Rule
IsNotAValidMoveRule --|> Rule

HasEmptyParametersRule -down-|> PieceTypeSharedRules
IsFriendlyFireRule -down-|> PieceTypeSharedRules
IsJumpingRule -down-|> PieceTypeSharedRules
IsMovingIntoCheckRule -down-|> PieceTypeSharedRules
KingIsValidBasicMoveRule -down-|> PieceTypeSharedRules
KingIsValidCastlingRule --|> PieceTypeSharedRules
IsNotAValidMoveRule -down-|> PieceTypeSharedRules

'-----'
'Notes'
'-----'
note right of KingIsValidMoveRulesEngine {
    If a king does not perform a friendly
    fire on one of its own pieces, if it's
    not jumping, if it doesn't create a check
    on itself, but it does perform a
    valid basic move or it is performing a
    valid castling move it is a valid move.
    Otherwise it's not a valid move.
}

@enduml
