@startuml

'--------------'
'Hidden members'
'--------------'
hide empty members

'----'
'Move'
'----'
class MoveBuilder {
    - {static} aiMoveDirector
    - {static} rookMoveBuilder
    + changeTurn()
    + enableValidMoves()
    + moveRookIfCastling()
    + performFromMove()
    + performResetMove()
    + performToMove()
    + resetFrom()
    + setKingFieldColors()
    + setMove()
    + setPieceTypeSpecificAttributes()
    + build()
}

class Move {
    - pieceType
    - from
    - to
    + isDuringAMove()
    + isFrom()
    + isValid()
    + setFrom()
    + setTo()
}

class Game {
    - {static} moveBuilder
    - chessboard
    - players
    - move
    + {static} create()
    + {static} restart()
    + changeTurn()
    + handleButtonClick()
}

class KingIsValidCastlingRule {
    + isValidCastling()
}

class AiMoveDirector {
    + performAiMove()
}

class PieceType {
    - color
    - hasBeenKickedOffTheBoard
    - isPawnBeingPromoted
    + getName()
    + getNextPawnPromotion()
    + getValue()
    + isValidMove()
    + setPieceTypeSpecificAttributes()
}

class Field {
    - BackgroundColorRulesEngine
    - id
    - code
    - coordinates
    - pieceType
    - backgroundColor
    - value
    - relativeValue
    - isValidFrom
    - hasValidTo
    - isAttacking
    - isUnderAttack
    - isCheckMate
    - isStaleMate
    + isActivePlayerField()
    + isInCheckNow()
    + isMovingIntoCheck()
    + isNotAbleToMove()
    + isValid()
    + setAttackingColors()
}

'---------'
'Relations'
'---------'
Game --* Move
Game -right-* MoveBuilder
MoveBuilder ..> KingIsValidCastlingRule
MoveBuilder --> MoveBuilder : move rook if castling
MoveBuilder -down-* AiMoveDirector
MoveBuilder ..> Move
Move -left-* PieceType
Move --* Field

@enduml
