@startuml

'--------------'
'Hidden members'
'--------------'
hide empty members

'----'
'Move'
'----'
abstract class PieceType {
    - color
    - hasBeenKickedOffTheBoard
    - isBeingPromoted
    + getName()
    + getNextPawnPromotion()
    + getValue()
    + isValidMove()
    + setPieceTypeSpecificAttributes()
}

class Pawn {
    - {static} pawnIsValidMoveRulesEngine
    - {static} pawnMayBeCapturedEnPassantRulesEngine
}

class IsValidMoveParameter {
    - chessboard
    - from
    - to
    - isOpponent
}

interface RulesEngine {
    - rules
    + addRule()
    + process()
}

interface Rule {
    + isApplicable()
    + getResult()
}

'---------'
'Relations'
'---------'
PieceType <|-- Pawn
Pawn *-- PawnIsValidMoveRulesEngine
PawnIsValidMoveRulesEngine -up-|> RulesEngine
PawnIsValidMoveRulesEngine .up[#blue].> IsValidMoveParameter

HasEmptyParametersRule -up-* PawnIsValidMoveRulesEngine
IsFriendlyFireRule -up-* PawnIsValidMoveRulesEngine
IsJumpingRule -up-* PawnIsValidMoveRulesEngine
IsMovingIntoCheckRule -up-* PawnIsValidMoveRulesEngine
PawnIsValidBasicMoveRule -up-* PawnIsValidMoveRulesEngine
PawnIsNotValidDirectionRule -up-* PawnIsValidMoveRulesEngine
PawnIsValidBaselineMoveRule -up-* PawnIsValidMoveRulesEngine
PawnIsValidCaptureMoveRule -up-* PawnIsValidMoveRulesEngine
PawnIsValidEnPassantMoveRule -up-* PawnIsValidMoveRulesEngine
IsNotAValidMoveRule -up-* PawnIsValidMoveRulesEngine

HasEmptyParametersRule -down-|> Rule
IsFriendlyFireRule -down-|> Rule
IsJumpingRule -down-|> Rule
IsMovingIntoCheckRule -down-|> Rule
PawnIsValidBasicMoveRule -down-|> Rule
PawnIsNotValidDirectionRule -down-|> Rule
PawnIsValidBaselineMoveRule -down-|> Rule
PawnIsValidCaptureMoveRule -down-|> Rule
PawnIsValidEnPassantMoveRule -down-|> Rule
IsNotAValidMoveRule -down-|> Rule

HasEmptyParametersRule -down-|> PieceTypeSharedRules
IsFriendlyFireRule -down-|> PieceTypeSharedRules
IsMovingIntoCheckRule -down-|> PieceTypeSharedRules
PawnIsValidBasicMoveRule -down-|> PieceTypeSharedRules
PawnIsNotValidDirectionRule -down-|> PieceTypeSharedRules
PawnIsValidBaselineMoveRule -down-|> PieceTypeSharedRules
PawnIsValidCaptureMoveRule -down-|> PieceTypeSharedRules
PawnIsValidEnPassantMoveRule -down-|> PieceTypeSharedRules
IsNotAValidMoveRule -down-|> PieceTypeSharedRules

'-----'
'Notes'
'-----'
note top of PawnIsValidMoveRulesEngine {
    If a pawn does not perform a friendly
    fire on one of its own pieces, if it's
    not jumping, if it doesn't create a check
    on its own king, but it does perform a
    valid basic move, a valid capture move or
    a valid en passant move, all in the right
    direction it is a valid move. Otherwise
    it's not a valid move.
}

@enduml
