@startuml

'--------------'
'Hidden members'
'--------------'
hide empty members

'----'
'Move'
'----'
abstract class PieceType {
    - color
    - hasBeenKickedOffTheBoard
    - isBeingPromoted
    + getName()
    + getNextPawnPromotion()
    + getValue()
    + isValidMove()
    + setPieceTypeSpecificAttributes()
}

class Queen {
    - {static} queenIsValidMoveRulesEngine
}

class IsValidMoveParameter {
    - chessboard
    - from
    - to
    - isOpponent
}

interface RulesEngine {
    - rules
    + addRule()
    + process()
}

interface Rule {
    + isApplicable()
    + getResult()
}

'---------'
'Relations'
'---------'
PieceType <|-down- Queen
Queen *-- QueenIsValidMoveRulesEngine
QueenIsValidMoveRulesEngine -up-|> RulesEngine
QueenIsValidMoveRulesEngine .left[#blue].> IsValidMoveParameter

HasEmptyParametersRule -up-* QueenIsValidMoveRulesEngine
IsFriendlyFireRule -up-* QueenIsValidMoveRulesEngine
IsJumpingRule -up-* QueenIsValidMoveRulesEngine
IsMovingIntoCheckRule -up-* QueenIsValidMoveRulesEngine
QueenIsValidBasicMoveRule -up-* QueenIsValidMoveRulesEngine
IsNotAValidMoveRule -up-* QueenIsValidMoveRulesEngine

HasEmptyParametersRule --|> Rule
IsFriendlyFireRule --|> Rule
IsJumpingRule --|> Rule
IsMovingIntoCheckRule --|> Rule
QueenIsValidBasicMoveRule --|> Rule
IsNotAValidMoveRule --|> Rule

HasEmptyParametersRule -down-|> PieceTypeSharedRules
IsFriendlyFireRule -down-|> PieceTypeSharedRules
IsJumpingRule --|> PieceTypeSharedRules
IsMovingIntoCheckRule -down-|> PieceTypeSharedRules
QueenIsValidBasicMoveRule -down-|> PieceTypeSharedRules
IsNotAValidMoveRule -down-|> PieceTypeSharedRules

'-----'
'Notes'
'-----'
note right of QueenIsValidMoveRulesEngine {
    If a queen does not perform a friendly
    fire on one of its own pieces, if it's
    not jumping, if it doesn't create a check
    on its own king, but it does perform a
    valid basic move it is a valid move. Otherwise
    it's not a valid move.
}

@enduml
