@startuml

'--------------'
'Hidden members'
'--------------'
hide empty members

'----'
'Move'
'----'
abstract class PieceType {
    - color
    - hasBeenKickedOffTheBoard
    - isBeingPromoted
    + getName()
    + getNextPawnPromotion()
    + getValue()
    + isValidMove()
    + setPieceTypeSpecificAttributes()
}

class Queen {
    - {static} queenIsValidMoveRulesEngine
}

class IsValidMoveParameter {
    - chessboard
    - from
    - to
    - isOpponent
}

interface RulesEngine {
    - rules
    + addRule()
    + process()
}

interface Rule {
    + isApplicable()
    + getResult()
}

'---------'
'Relations'
'---------'
PieceType <|-down- Queen
Queen *-- QueenIsValidMoveRulesEngine
QueenIsValidMoveRulesEngine -up-|> RulesEngine
QueenIsValidMoveRulesEngine -up-|> PieceTypeSharedRules
QueenIsValidMoveRulesEngine .left[#blue].> IsValidMoveParameter
HasEmptyParametersRule -up-* QueenIsValidMoveRulesEngine
IsFriendlyFireRule -up-* QueenIsValidMoveRulesEngine
IsJumpingRule -up-* QueenIsValidMoveRulesEngine
IsMovingIntoCheckRule -up-* QueenIsValidMoveRulesEngine
QueenIsValidBasicMoveRule -up-* QueenIsValidMoveRulesEngine
IsNotValidRule -up-* QueenIsValidMoveRulesEngine
HasEmptyParametersRule --|> Rule
IsFriendlyFireRule --|> Rule
IsJumpingRule --|> Rule
IsMovingIntoCheckRule --|> Rule
QueenIsValidBasicMoveRule --|> Rule
IsNotValidRule --|> Rule

@enduml
