@startuml

'--------------'
'Hidden members'
'--------------'
hide empty members

'----'
'Move'
'----'
abstract class PieceType {
    - color
    - hasBeenKickedOffTheBoard
    - isBeingPromoted
    + getName()
    + getNextPawnPromotion()
    + getValue()
    + isValidMove()
    + setPieceTypeSpecificAttributes()
}

class Rook {
    - {static} rookIsValidMoveRulesEngine
}

class IsValidMoveParameter {
    - chessboard
    - from
    - to
    - isOpponent
}

interface RulesEngine {
    - rules
    + addRule()
    + process()
}

interface Rule {
    + isApplicable()
    + getResult()
}

'---------'
'Relations'
'---------'
PieceType <|-down- Rook
Rook *-- RookIsValidMoveRulesEngine
RookIsValidMoveRulesEngine -up-|> RulesEngine
RookIsValidMoveRulesEngine .left[#blue].> IsValidMoveParameter

HasEmptyParametersRule -up-* RookIsValidMoveRulesEngine
IsFriendlyFireRule -up-* RookIsValidMoveRulesEngine
IsJumpingRule -up-* RookIsValidMoveRulesEngine
IsMovingIntoCheckRule -up-* RookIsValidMoveRulesEngine
RookIsValidBasicMoveRule -up-* RookIsValidMoveRulesEngine
IsNotAValidMoveRule -up-* RookIsValidMoveRulesEngine

HasEmptyParametersRule --|> Rule
IsFriendlyFireRule --|> Rule
IsJumpingRule --|> Rule
IsMovingIntoCheckRule --|> Rule
RookIsValidBasicMoveRule --|> Rule
IsNotAValidMoveRule --|> Rule

HasEmptyParametersRule -down-|> PieceTypeSharedRules
IsFriendlyFireRule -down-|> PieceTypeSharedRules
IsJumpingRule --|> PieceTypeSharedRules
IsMovingIntoCheckRule -down-|> PieceTypeSharedRules
RookIsValidBasicMoveRule -down-|> PieceTypeSharedRules
IsNotAValidMoveRule -down-|> PieceTypeSharedRules

'-----'
'Notes'
'-----'
note right of RookIsValidMoveRulesEngine {
    If a rook does not perform a friendly
    fire on one of its own pieces, if it's
    not jumping, if it doesn't create a check
    on its own king, but it does perform a
    valid basic move it is a valid move. Otherwise
    it's not a valid move.
}

@enduml
