@startuml

'--------------'
'Hidden members'
'--------------'
hide empty members

'----'
'Move'
'----'
abstract class PieceType {
    - color
    - hasBeenKickedOffTheBoard
    - isBeingPromoted
    + getName()
    + getNextPawnPromotion()
    + getValue()
    + isValidMove()
    + setPieceTypeSpecificAttributes()
}

class Rook {
    - {static} rookIsValidMoveRulesEngine
}

class IsValidMoveParameter {
    - chessboard
    - from
    - to
    - isOpponent
}

interface RulesEngine {
    - rules
    + addRule()
    + process()
}

interface Rule {
    + isApplicable()
    + getResult()
}

'---------'
'Relations'
'---------'
PieceType <|-down- Rook
Rook *-- RookIsValidMoveRulesEngine
RookIsValidMoveRulesEngine -up-|> RulesEngine
RookIsValidMoveRulesEngine -up-|> PieceTypeSharedRules
RookIsValidMoveRulesEngine .left[#blue].> IsValidMoveParameter
HasEmptyParametersRule -up-* RookIsValidMoveRulesEngine
IsFriendlyFireRule -up-* RookIsValidMoveRulesEngine
IsJumpingRule -up-* RookIsValidMoveRulesEngine
IsMovingIntoCheckRule -up-* RookIsValidMoveRulesEngine
RookIsValidBasicMoveRule -up-* RookIsValidMoveRulesEngine
IsNotValidRule -up-* RookIsValidMoveRulesEngine
HasEmptyParametersRule --|> Rule
IsFriendlyFireRule --|> Rule
IsJumpingRule --|> Rule
IsMovingIntoCheckRule --|> Rule
RookIsValidBasicMoveRule --|> Rule
IsNotValidRule --|> Rule

@enduml
